### ISSUE TITLE
Process breaks with small flat time series and reports unclear error

### ISSUE THREAD

**Issue by badbayesian** [skoestlmeier/ICSS#1]
Hello!

I was playing around with some view count data and found that if the data set is too flat, the process will not converge. However, instead of returning an NA. An unhelpful error is raise. The data here is the difference in view counts over time.

`test <- c(0, 0, 2, 1, 0, -1, 1, 0, 1, 0, -1, 1, 1, 5, -2, -1, -1, -1, 
2, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, -3, 1, -1, -1, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, -1, 0, 0, 0, 0, 0, 0, 0)`

`> ICSS(test)`
`Error in while (exceeds) { : missing value where TRUE/FALSE needed`

This appears to be happening because on line 116-117 as `CenteredCusumValues` returns a list of NAs  at some point in the while loop due to all the values being equal, as in this case (0 0 0 0 0 0 0). Then, `check_critical_value(Dk_step2b)` set `tmp$exceeds = NA` which breaks the `while(exceed)` loop on line 114 and line 99.

I'll open up a pull request once I fix the bug. A quick `is_na(tmp$exceeds)` would fix this issue.

**Comment by badbayesian** [comment]
I found a second bug that is slightly different, although in the same genre. This is another diff viewer count data. It seems like if there is some time series with a large spike at the end, the code will break due to line 56 as `potential_change_points` returns an NA. This is due to trying an index value outside the array but the error doesnt show up until line 58 where the index access actually happens as `to = NA`.

`test2 = c(0, 0, -1, 0, 0, 0, 0, -1, 2, 1, -1, -1, 1, -1, 1, 1, -1, 0, 
0, 0, 0, -1, 0, 1, 0, -1, 1, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, -1, 0, 0, -1, 1, 1, 0, 0, 0, 0, 0, 0, -2, 2, 0, 0, 
0, 0, -1, 1, 0, 0, -1, 0, 0, 0, 1, -1, 1, -1, 0, 1, 0, 0, -1, 
0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 
0, 2, -2, 1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 
-2, 2, 0, -1, 1, 0, 0, 0, 0, -1, 1, -1, 1, 0, -1, 1, 1, 14)`

`ICSS(test2)`
`Error in from:to : NA/NaN argument`

This error also happens with the following code:
`x = rnorm(100)`
`y = c(x, 1e5)`
`ICSS(y)`

Notice that `ICSS(c(1e5, x))` does return the correct value.

**Comment by badbayesian** [comment]
Thanks for merging!

**Comment by badbayesian** [comment]
Thanks for merging!

**Comment by skoestlmeier** [comment]
Thanks @badbayesian for your very valuable contribution. It significantly improves the quality of this R-package! I merged your pull request and worked on your reported bug #2. I have added additional checks so that `ICSSS(test)` gives an appropriate warning and `ICSS(test2)` returns `NA`.

**Comment by badbayesian** [comment]
Thank you @skoestlmeier for coding up my mom's dissertation in R! She is really happy about it. :)
